name: Deploy
on:
  push:
    branches:
      -  main
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python requirements Plugin and Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS_DEBUG: 1
        uses: serverless/github-action@v3
        with:
          args: -c "serverless plugin install --name serverless-vpc-discovery serverless-python-requirements && serverless deploy"
      

